#!/bin/bash

#A simple notify script for now-playing songs
#on mpd. This script uses notify-send and
#mpc to get the current song information.

#Requirements : 
# - mpd
# - mpc
# - notify-send (libnotify)

# Author : Wolfgang Mueller
# You can use, edit and redistribute this script in any way you like.
# (Just make sure not to hurt any kittens)

#Configuration-------------------------------------------------------

#The music directory that contains the music and cover files
MUSIC_DIR="/media/Daten/MP3/My_Music"

#The default cover to use (optional, leave empty for no default cover)
DEFAULT_ART=""

#The following track metadata delimiters can be changed.
#You can find all possible delimiters in the 'mpc' manpage.
#It's also possible to use tags like <u></u> and <i></i>

#How to format artist/album information
A_FORMAT="%artist%[ (%album%)]"

#How to format title information
T_FORMAT="%title%"

#Regex expression used for image search
IMG_REG="\.(jpg|jpeg|png)"

#Regex expression used for image name
NAME_REG="(front|cover|art)"

#Title of the notification
NOTIFY_TITLE="Now Playing"

#--------------------------------------------------------------------

#determine file
file="$(mpc current -f %file%)"

#check if anything is playing at all
[[ -z $file ]] && exit 1

#Get title info
title="$(mpc current -f "$A_FORMAT")"

#Get song info
song="$(mpc current -f "$T_FORMAT")"

#Art directory
art="$MUSIC_DIR/${file%/*}"

#find every file that is either png or jpg
images="$(find "$art/"* -type f | egrep -i "$IMG_REG")"

artfiles="$(egrep -i "$NAME_REG" <<< "$images")" 
cover="$(head -n1 <<< "$artfiles")"
[[ -z $cover ]] && [[ -n $DEFAULT_ART ]] && cover="$DEFAULT_ART"

#check if art is available
# --hint=int:transient:1 is needed, because gnome-shell will keep the notification in its bar.
# using 'hint' they'll be removed automatically (gnome-shell 3.01)
if [[ -n $cover ]]; then
	notify-send -t 5000 --hint=int:transient:1 "$NOTIFY_TITLE" "$title\n$song" -i "$cover"
else
	notify-send -t 5000 --hint=int:transient:1 "$NOTIFY_TITLE" "$title\n$song"
fi

